In [1]:
import numpy as np

# Numpy Arrays

In [2]:
# https://jalammar.github.io/visual-numpy/

In [3]:
my_list = [10,20,30,40,50]
print(type(my_list))

<class 'list'>


In [4]:
np_array = np.array(my_list)
print(type(np_array))

<class 'numpy.ndarray'>


In [5]:
np_array

array([10, 20, 30, 40, 50])

In [6]:
print(np.ones(5))
print(np.zeros(5))
print(np.random.random(5))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0.35874566 0.47164376 0.28815461 0.71781962 0.22356976]


# Array Arithmetic

In [7]:
myList1 = [1,2]
myList2 = [3,4]
print("List 1: ",myList1)
print("List 2: ",myList2)

List 1:  [1, 2]
List 2:  [3, 4]


In [8]:
my_numpy_array1 = np.array(myList1)
my_numpy_array2 = np.array(myList2)
print("1. Numpy Array is: ",my_numpy_array1)
print("2. Numpy Array is: ",my_numpy_array2)

1. Numpy Array is:  [1 2]
2. Numpy Array is:  [3 4]


In [9]:
myList1 + myList2

[1, 2, 3, 4]

In [10]:
my_numpy_array1 + my_numpy_array2 # 1+3=4 first element, 2+4=6 second element

array([4, 6])

In [11]:
print(my_numpy_array1 - my_numpy_array2)
print(my_numpy_array1 * my_numpy_array2)
print(my_numpy_array1 / my_numpy_array2)

[-2 -2]
[3 8]
[0.33333333 0.5       ]


In [12]:
my_numpy_array1 * 5

array([ 5, 10])

# Arange & Indexing

In [13]:
print("List: ",list(range(0,10)))
print("Numpy Array: ",np.arange(0,10))

List:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy Array:  [0 1 2 3 4 5 6 7 8 9]


In [14]:
my_np_array = np.arange(0,10)

print("First element: ",my_np_array[0],"\n","Last Element: ",my_np_array[-1])
print("Slicing: ", my_np_array[1:10:2])
print("Reverse: ", my_np_array[::-1])

First element:  0 
 Last Element:  9
Slicing:  [1 3 5 7 9]
Reverse:  [9 8 7 6 5 4 3 2 1 0]


In [15]:
print(my_np_array.max())
print(my_np_array.min())
print(my_np_array.sum())
print("\n**********\n")
print(np.random.rand(4,4),"\n")
print(np.random.randint(1,300,5))

9
0
45

**********

[[0.55219604 0.17195039 0.95832016 0.19986909]
 [0.86171303 0.42887602 0.24490513 0.88097695]
 [0.92387721 0.97220295 0.33689858 0.51070248]
 [0.7000118  0.9186977  0.75231983 0.41337707]] 

[199 223  17 225 248]


# Matrix

In [16]:
# row * column
matrix = np.array([[1,2],[3,4]])
one_matrix = np.ones((2,2))

print(matrix)
print()
print(one_matrix)

[[1 2]
 [3 4]]

[[1. 1.]
 [1. 1.]]


In [17]:
# Matrix Arithmetic
matrix + one_matrix

array([[2., 3.],
       [4., 5.]])

In [18]:
matrix.shape

(2, 2)

In [19]:
# matrix multiplication
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[5,15],[25,35]])

print("First Matrix\n",first_array)
print(first_array.shape)
print()
print("Second Matrix\n",second_array)
print(second_array.shape)

First Matrix
 [[10 20]
 [30 40]]
(2, 2)

Second Matrix
 [[ 5 15]
 [25 35]]
(2, 2)


In [20]:
# 1.nin sütunu 2.satırına eşit olmalı. 1--> 2x2 , 2--> 2x2
first_array * second_array # bu normal

array([[  50,  300],
       [ 750, 1400]])

In [21]:
# dot product
matrix1 = np.array([[10,20],[30,40],[50,60]])
matrix2 = np.array([[1,3],[5,7]])

print(matrix1)
print(matrix1.shape)
print()
print(matrix2)
print(matrix2.shape)

[[10 20]
 [30 40]
 [50 60]]
(3, 2)

[[1 3]
 [5 7]]
(2, 2)


In [22]:
matrix1.dot(matrix2) # 3x[2] * [2]x2 = 2x2 

array([[110, 170],
       [230, 370],
       [350, 570]])

# Numpy Operations

In [23]:
new_array = np.random.randint(1,100,20)

print(new_array)

[89 27 93 67 29 49 97 48 23 61 35 81 94  4 68 59  7 37 15 35]


In [24]:
print(new_array>30)
print()
print(new_array[new_array>30])

[ True False  True  True False  True  True  True False  True  True  True
  True False  True  True False  True False  True]

[89 93 67 49 97 48 61 35 81 94 68 59 37 35]


In [26]:
# Transpose & Reshape
matrix_array = np.array([[10,20],[30,40],[50,60]])
print(matrix_array)
print(matrix_array.shape)
print()
print("Transpose: \n", matrix_array.transpose())
print()
print(matrix_array.T)

[[10 20]
 [30 40]
 [50 60]]
(3, 2)

Transpose: 
 [[10 30 50]
 [20 40 60]]

[[10 30 50]
 [20 40 60]]


In [29]:
random_array = np.random.random((6,1))
print(random_array)
print()
print(random_array.shape)

[[0.47987755]
 [0.31062094]
 [0.34237586]
 [0.92735271]
 [0.23488684]
 [0.0894928 ]]

(6, 1)


In [30]:
random_array.reshape(2,3)

array([[0.47987755, 0.31062094, 0.34237586],
       [0.92735271, 0.23488684, 0.0894928 ]])

In [44]:
# Denklem çözme - gerek olmayabilir 
# 2x + 3y = 8 and 5x + 7y = 19
# coefficient (katsayılar)
A = np.array([[2,3],[5,7]])
print(A)
print()

# constant - sabitler
b = np.array([8,19])
print(b)
print()

solution = np.linalg.solve(A,b)
print(f"x: {solution[0]}")
print(f"y: {solution[1]}")

[[2 3]
 [5 7]]

[ 8 19]

x: 1.0
y: 2.0
